version: '3.8'

services:
  php-apache-environment:
    container_name: php-sandbox
    image: php:7.4-apache
    volumes:
      - ./:/var/www/html/
      - ./php.ini:/usr/local/etc/php/php.ini
    ports:
      - 8000:80
